// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PIMS_backend.Migrations
{
    [DbContext(typeof(ProductInventoryManagementDbContext))]
    [Migration("20250329150955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PIMS_backend.Classes.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 39.99m,
                            ProductName = "RAM Stick",
                            Quantity = 74
                        },
                        new
                        {
                            Id = 2,
                            Price = 247.99m,
                            ProductName = "Graphics Card",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Price = 535m,
                            ProductName = "Laptop",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            Price = 99.99m,
                            ProductName = "SSD",
                            Quantity = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
